#!/usr/bin/env python
#  See the pymilter project at http://bmsi.com/python/milter.html
#  based on Sendmail's milter API http://www.milter.org/milter_api/api.html
#  This code is open-source on the same terms as Python.

# # Olympe Network postfix sendquota milter
 # aya <yann.autissier@anotherservice.com>
# from http://pythonhosted.org/pymilter/milter-template_8py-example.html

import os, sys, time, getopt
import logging as log
import ConfigParser
import ldap
import MySQLdb
import Milter
import StringIO
from socket import AF_INET, AF_INET6
from Milter.utils import parse_addr
if True:
    from multiprocessing import Process as Thread
else:
    from threading import Thread

_release='0.1.1'

def usage():
    print """Usage: postquotad [options]

options:
    -d, --debug         debug mode
    -f, --foreground    do not daemonize
    -h, --help          print this message
    -q, --quiet         quiet mode
    -v, --version       print current version
"""

def version(version=""):
    print "postquotad v%s" % version

# Handle global options.
try:
    opts, args = getopt.getopt(sys.argv[1:], 'dfhqv', ['debug', 'foreground', 'help', 'quiet', 'version'])
except getopt.GetoptError as err:
    log.warning(str(err))
    sys.exit(2)

# Parse options
for opt, arg in opts:
    if opt == "-v":
        _verbose = True
    elif opt in ("-d", "--debug"):
        _debug = True
        log.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', datefmt='%Y/%m/%d %H:%M:%S', level=log.DEBUG)
    elif opt in ("-f", "--foreground"):
        _foreground = True
    elif opt in ("-h", "--help"):
        usage()
        sys.exit()
    elif opt in ("-q", "--quiet"):
        _quiet = True
        log.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', datefmt='%Y/%m/%d %H:%M:%S', level=log.ERROR)
    elif opt in ("-v", "--version"):
        version(_release)
        sys.exit()
    else:
        assert False, "unhandled option"

class myLdap():

    def __init__(self,config):
        self.ldaphost = config.get('ldap', 'host') if config.has_option('ldap', 'host') else 'localhost'
        self.ldapport = config.get('ldap', 'port') if config.has_option('ldap', 'port') else '389'
        self.ldapbase = config.get('ldap', 'base') if config.has_option('ldap', 'base') else 'dc=dns'
        self.ldapfilter = config.get('ldap', 'filter') if config.has_option('ldap', 'filter') else '(objectclass=posixAccount)'
        # useful only for debug
        if config.has_option('ldap', 'mail'):
            self.ldapmail = config.get('ldap', 'mail')
        self.attributes = ['owner','uid']
        try:
            self.l = ldap.initialize('ldap://' + self.ldaphost + ':' + self.ldapport)
            self.l.protocol_version = ldap.VERSION3
        except ldap.LDAPError, error:
            print error

    def getUser(self, mail):
        baseDN = self.ldapbase
        searchScope = ldap.SCOPE_SUBTREE
        retrieveAttributes = self.attributes
        # debug
        try:
            user = self.ldapmail
            log.debug( 'Overriding SMTP AUTH user %s with %s', mail, self.ldapmail )
        except:
            user = mail
        searchFilter = '(&' + self.ldapfilter + '(mail=' + user + '))'

        try:
            ldap_result_id = self.l.search(baseDN, searchScope, searchFilter, retrieveAttributes)
            result_set = []
            while 1:
                result_type, result_data = self.l.result(ldap_result_id, 0)
                if (result_data == []):
                    break
                else:
                    if result_type == ldap.RES_SEARCH_ENTRY:
                        result_set.append(result_data)
            for entries in result_set:
                for entry in entries:
                    dn,attributes = entry
                    try:
                        for owner in attributes['owner']:
                            if owner == 'uid=admin,ou=Users,dc=olympe,dc=in,dc=dns':
                                for uid in attributes['uid']:
                                    return uid
                            else:
                                return owner.split(",")[0].lstrip('uid=')
                    except:
                        account = dn.split(",")
                        if len(account) == 5 and account[2] == 'dc=olympe':
                            try:
                                for uid in attributes['uid']:
                                    return uid
                            except:
                                print 'ERROR: ldap uid not found for dn: ' + dn + ' (' + mail + ')'
                        else:
                            print 'ERROR: ldap owner not found for dn: ' + dn + ' (' + mail + ')'
        except ldap.LDAPError, error:
            print error
        return False

class mySql():

    def __init__(self,config):
        self.hostname = config.get('mysql', 'hostname') if config.has_option('mysql', 'hostname') else 'localhost'
        self.database = config.get('mysql', 'database') if config.has_option('mysql', 'database') else 'postquota'
        self.username = config.get('mysql', 'username') if config.has_option('mysql', 'hostname') else 'postquota'
        self.password = config.get('mysql', 'password') if config.has_option('mysql', 'hostname') else 'postquota'
        try:
            self.m = MySQLdb.connect(host=self.hostname,user=self.username,passwd=self.password,db=self.database)
        except MySQLdb.MySQLError, error:
            print error

    def getUid(self, user):
        try:
            cur = self.m.cursor()
            cur.execute("SELECT user_id FROM users WHERE user_name = '" + user + "';")
            try: 
                return str(cur.fetchone()[0])
            except:
                print 'ERROR: mysql uid not found for user: ' + user
        except MySQLdb.MySQLError, error:
            print error
        return False

    def getQuota(self, uid):
        try:
            cur = self.m.cursor()
            cur.execute("SELECT quota_used, quota_max FROM user_quota WHERE user_id = '" + uid + "' and quota_id = 15;")
            try: 
                quota = cur.fetchone()
                return {'used': int(quota[0]), 'max': int(quota[1])}
            except:
                print 'ERROR: mysql quota not found for uid: ' + uid
        except MySQLdb.MySQLError, error:
            print error
        return False

    def updateQuota(self, uid, quota):
        if not quota or not uid:
            return False
        try:
            cur = self.m.cursor()
            cur.execute("UPDATE user_quota SET quota_used = '" + str(quota) + "' WHERE user_id = '" + uid + "' and quota_id = 15;")
            self.m.commit()
            return True
        except MySQLdb.MySQLError, error:
            print error
        return False

class myMilter(Milter.Base):

    def __init__(self):  # A new instance with each new connection.
        self.id = Milter.uniqueID()  # Integer incremented with each call.
        self.ldap = myLdap(self.config)
        self.mysql = mySql(self.config)

    # each connection runs in its own thread and has its own myMilter
    # instance.  Python code must be thread safe.  This is trivial if only stuff
    # in myMilter instances is referenced.
    @Milter.noreply
    def connect(self, IPname, family, hostaddr):
        try:
            self.IP = hostaddr[0]
            self.port = hostaddr[1]
            if family == AF_INET6:
                self.flow = hostaddr[2]
                self.scope = hostaddr[3]
            else:
                self.flow = None
                self.scope = None
        except:
            log.info("ERROR: Unable to get hostaddr from %s" % IPname)
            # self.setreply('550','5.7.1','ERROR: Unable to get hostaddr')
            # return Milter.REJECT
        self.IPname = IPname  # Name from a reverse IP lookup
        self.H = None
        self.fp = None
        self.receiver = self.getsymval('j')
        # log.info("connect from %s at %s" % (IPname, hostadsdr) )

        return Milter.CONTINUE

    ##  def hello(self,hostname):
    def hello(self, heloname):
        self.H = heloname
#        log.info("HELO %s" % heloname)
#        if heloname.find('.') < 0:  # illegal helo name
#            # NOTE: example only - too many real braindead clients to reject on this
#            self.setreply('550','5.7.1','Sheesh people!  Use a proper helo name!')
#            return Milter.REJECT
        return Milter.CONTINUE

    ##  def envfrom(self,f,*str):
    def envfrom(self, mailfrom, *str):
        self.F = mailfrom
        self.R = []  # list of recipients
        self.fromparms = Milter.dictfromlist(str)   # ESMTP parms
        self.user = self.getsymval('{auth_authen}') # authenticated user
        # implement quota
        if self.user:
            # log.info("mail:", self.user, *str)
            self.ldapUser = self.ldap.getUser(self.user)
            if not self.ldapUser:
                self.setreply('554','5.7.1','This user doesn\'t have a valid ldap account (' + self.user + ')')
                log.info('Unable to find user ' + self.user + ' ' + mailfrom + ' from ' + self.IPname )
                return Milter.REJECT
            self.mysqlUid = self.mysql.getUid(self.ldapUser)
            if not self.mysqlUid:
                self.setreply('554','5.7.1','This user doesn\'t have a valid mysql account (' + self.user + ')')
                log.info('Unable to find uid ' + self.user + ' ' + mailfrom + ' from ' + self.IPname + ')')
                return Milter.REJECT
            self.quota = self.mysql.getQuota(self.mysqlUid)
            if not self.quota:
                self.setreply('554','5.7.1','This user doesn\'t have a valid quota (' + self.user + ')')
                log.info('Unable to find uid ' + self.user + ' ' + mailfrom + ' from ' + self.IPname + ')')
                return Milter.REJECT
        self.fp = StringIO.StringIO()
        return Milter.CONTINUE

    ##  def envrcpt(self, to, *str):
    @Milter.noreply
    def envrcpt(self, to, *str):
        rcptinfo = to,Milter.dictfromlist(str)
        self.R.append(rcptinfo)
        return Milter.CONTINUE

    @Milter.noreply
    def header(self, name, hval):
        self.fp.write("%s: %s\n" % (name,hval))     # add header to buffer
        return Milter.CONTINUE

    # @Milter.noreply
    def eoh(self):
        self.fp.write("\n")                         # terminate headers
        # implement quota
        try:
            self.quota
        except:
            mailto,info = self.R[0]
            log.info('Delivering mail for ' + mailto + ' from ' + self.IPname)
            return Milter.CONTINUE
        if self.quota['used'] + len(self.R) > self.quota['max']:
            self.setreply('554','5.7.1','User quota exceeded ('+str(self.quota['max'])+') ! Please try again later')
            log.info('Quota exceeded for user ' + self.ldapUser + ' <' + self.user + '> (' + str(self.quota['used']) + ' + ' + str(len(self.R)) + ' > ' + str(self.quota['max']) + ') from ' + self.IPname)
            return Milter.REJECT
        else:
            if self.mysql.updateQuota(self.mysqlUid, self.quota['used'] + len(self.R)):
                log.info('Quota updated for user ' + self.ldapUser + ' <' + self.user + '> (' + str(self.quota['used'] + len(self.R)) + '/' + str(self.quota['max']) + ') from ' + self.IPname)
                return Milter.CONTINUE
            else:
                self.setreply('550','5.7.1','Internal error while updating your quota ! Please try again later')
                log.info('Unable to update quota for user ' + self.ldapUser + ' <' + self.user + '> (used: ' + str(self.quota['used']) + ', count: ' + str(len(self.R)) + ') from ' + self.IPname)
                return Milter.REJECT

    @Milter.noreply
    def body(self, chunk):
        self.fp.write(chunk)
        return Milter.CONTINUE

    def eom(self):
        self.fp.seek(0)
        # many milter functions can only be called from eom()
        # example of adding a Bcc:
        # self.addrcpt('<%s>' % 'spy@example.com')
        return Milter.ACCEPT

    def close(self):
        # always called, even when abort is called.  Clean up
        # any external resources here.
        return Milter.CONTINUE

    def abort(self):
        # client disconnected prematurely
        return Milter.CONTINUE

def background():
    pass

## ===

def main():
    bt = Thread(target=background)
    bt.start()
    Milter.factory = myMilter
    myMilter.config = ConfigParser.RawConfigParser()
    myMilter.config.read( ['/etc/postquotad/postquotad.conf', '/usr/local/etc/hosting.ini', '/dns/in/olympe/etc/settings/hosting.ini'] )
    socket = myMilter.config.get('daemon', 'socket') if myMilter.config.has_option('daemon', 'socket') else 'inet:10123@127.0.0.1'
    timeout = myMilter.config.get('daemon', 'timeout') if myMilter.config.has_option('daemon', 'timeout') else 60
    # Register to have the Milter factory create instances of your class:
    flags = Milter.CHGBODY + Milter.CHGHDRS + Milter.ADDHDRS
    flags += Milter.ADDRCPT
    flags += Milter.DELRCPT
    Milter.set_flags(flags)
    log.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', datefmt='%Y/%m/%d %H:%M:%S', level=log.INFO)
    log.info('postquotad starting')
    try:
        Milter.runmilter("pythonfilter",socket,timeout)
    except Milter.error, error:
        log.error( '%s (socket : %s)' % (error, socket) )
    bt.join()
    log.info('postquotad shutdown')

def daemonize():
    try:
        pid = os.fork()
    except OSError, e:
        raise Exception, "%s [%d]" % (e.strerror, e.errno)

    if (pid == 0):   # The child
        os.setsid()
    else:
        os._exit(0)   # Exit parent
    return(0)

if __name__ == "__main__":
    # daemonize
    try:
        if _foreground:
            pass
    except:
        daemonize()
    # start main prog
    main()
    sys.exit()
